apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-data
  name: basket-data
spec:
  selector:
    matchLabels:
      io.kompose.service: basket-data
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: basket-data
    spec:
      containers:
      - image: redis
        imagePullPolicy: Never
        name: basket-data
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}

