apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: basketdata
  name: basketdata
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: basketdata
    spec:
      containers:
      - image: redis
        name: basketdata
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
