apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: webmvc
  name: webmvc
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webmvc
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: CallbackUrl
          value: http://localhost
        - name: CartUrl
          value: http://cart
        - name: CatalogUrl
          value: http://catalog
        - name: IdentityUrl
          value: http://192.168.1.4:5000
        - name: OrderUrl
          value: http://order
        image: tkousek/mvc
        name: webshop
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
